const STORAGE_KEY="creativeHubDashboardV3", LEGACY_KEYS=["creativeHubDashboardV2","creativeSubscriptionDashboardV1"];
const DEMO={reportMonth:"2026-08",subscriptions:[
{id:"s1",product:"Magnific",tool:"AI + Photo Download",plan:"Yearly",status:"Inactive",start:"2026-08-19",expiry:"",cost:"",email:"creative.team1010@gmail.com",reminderEmail:"",alertDays:7,initialTokens:"",purchaseNote:"",archived:false},
{id:"s2",product:"Magnific",tool:"AI + Photo Download",plan:"Yearly",status:"Inactive",start:"2026-08-19",expiry:"",cost:"",email:"creative.team.kbz999@gmail.com",reminderEmail:"",alertDays:7,initialTokens:"",purchaseNote:"",archived:false},
{id:"s3",product:"ChatGPT",tool:"AI + Content Creation",plan:"Monthly",status:"Active",start:"2026-08-19",expiry:"2026-09-19",cost:"24",email:"creative.team.kbz111@gmail.com",reminderEmail:"",alertDays:7,initialTokens:"",purchaseNote:"",archived:false}
],tokenEntries:[]};
const $=id=>document.getElementById(id); const clone=o=>JSON.parse(JSON.stringify(o));
function uid(p){return p+"_"+Date.now()+"_"+Math.random().toString(36).slice(2,7)}
function normalize(d){d=d||clone(DEMO);d.reportMonth=d.reportMonth||"2026-08";d.subscriptions=(d.subscriptions||[]).map(x=>({id:x.id||uid("s"),product:x.product||"",tool:x.tool||"",plan:x.plan||"Monthly",status:x.status||"Active",start:x.start||x.startDate||"",expiry:x.expiry||x.expireDate||"",cost:x.cost??"",email:x.email||"",reminderEmail:x.reminderEmail||"",alertDays:Number(x.alertDays??7),initialTokens:x.initialTokens??"",purchaseNote:x.purchaseNote||"",archived:!!x.archived}));d.tokenEntries=(d.tokenEntries||[]).map(x=>({...x,id:x.id||uid("t")}));return d}
function load(){try{let s=localStorage.getItem(STORAGE_KEY);if(s)return normalize(JSON.parse(s));for(const k of LEGACY_KEYS){let old=localStorage.getItem(k);if(old)return normalize(JSON.parse(old))}}catch(e){}return clone(DEMO)}
let state=load();
function save(){localStorage.setItem(STORAGE_KEY,JSON.stringify(state));$("saveStatus").textContent="Saved"}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
const fmt=n=>Number(n||0).toLocaleString(), money=n=>"$"+Number(n||0).toLocaleString(undefined,{maximumFractionDigits:2});
function dateText(iso){if(!iso)return"—";return new Date(iso+"T00:00:00").toLocaleDateString("en-GB",{day:"2-digit",month:"short",year:"numeric"})}
function monthName(m){let[y,mo]=m.split("-").map(Number);return new Date(y,mo-1,1).toLocaleDateString("en-US",{month:"long",year:"numeric"})}
function todayISO(){return new Date().toISOString().slice(0,10)} function dayDiff(a,b){return Math.ceil((new Date(b+"T00:00:00")-new Date(a+"T00:00:00"))/86400000)}
const visibleSubs=()=>state.subscriptions.filter(x=>!x.archived);
const selectedMonthEntries=()=>state.tokenEntries.filter(x=>!x.archived&&x.date?.slice(0,7)===state.reportMonth).sort((a,b)=>a.date.localeCompare(b.date));
const selectedYear=()=>Number(state.reportMonth.slice(0,4));
const selectedYearEntries=()=>state.tokenEntries.filter(x=>!x.archived&&x.date?.startsWith(String(selectedYear()))).sort((a,b)=>a.date.localeCompare(b.date));
function alerts(){let t=todayISO();return visibleSubs().filter(x=>x.expiry).map(x=>{let d=dayDiff(t,x.expiry),w=Number(x.alertDays??7);return d<0?{sub:x,type:"overdue",diff:d}:d<=w?{sub:x,type:"due",diff:d}:null}).filter(Boolean).sort((a,b)=>a.diff-b.diff)}
function render(){
 $("reportMonth").value=state.reportMonth;let subs=visibleSubs(),a=alerts(),entries=selectedMonthEntries(),total=subs.length,active=subs.filter(x=>x.status==="Active").length;
 let monthlyCost=subs.filter(x=>x.status==="Active"&&x.plan==="Monthly").reduce((s,x)=>s+Number(x.cost||0),0),used=entries.reduce((s,x)=>s+Number(x.tokens||0),0),tcost=entries.reduce((s,x)=>s+Number(x.cost||0),0),alloc=subs.filter(x=>x.product.toLowerCase().includes("magnific")).reduce((s,x)=>s+Number(x.initialTokens||0),0);
 $("totalSubs").textContent=total;$("activeSubs").textContent=active;$("activePct").textContent=(total?Math.round(active/total*100):0)+"% of total";$("overdueSubs").textContent=a.filter(x=>x.type==="overdue").length;$("monthlyCost").textContent=money(monthlyCost);$("monthTokens").textContent=fmt(used);$("alertCount").textContent=a.length+" alert"+(a.length===1?"":"s");
 $("alertList").innerHTML=a.length?a.map(o=>{let x=o.sub,l=o.type==="overdue"?Math.abs(o.diff)+" day(s) overdue":"Due in "+o.diff+" day(s)";return `<div class="alert-item ${o.type}"><div><div class="alert-title"><b>${esc(x.product)} — ${esc(x.tool)}</b><span class="alert-badge ${o.type}">${l}</span></div><div class="alert-meta">Expiry: ${dateText(x.expiry)} • Account: ${esc(x.email||"—")} • Reminder: ${esc(x.reminderEmail||"not set")}</div></div><div class="alert-actions"><button class="email-btn" onclick="sendReminder('${x.id}')">Send Email Alert</button><button class="small-btn edit" onclick="editSub('${x.id}')">Edit</button></div></div>`}).join(""):`<div class="info-box"><b>No due or overdue subscriptions.</b><p>Alerts will appear here inside the configured reminder window.</p></div>`;
 $("subRows").innerHTML=subs.map(x=>`<tr><td><b>${esc(x.product)}</b></td><td>${esc(x.tool)}</td><td>${esc(x.plan)}</td><td><span class="badge ${x.status.toLowerCase()}">${esc(x.status)}</span></td><td>${dateText(x.start)}</td><td>${dateText(x.expiry)}</td><td>${x.cost!==""?money(x.cost):"—"}</td><td>${x.initialTokens!==""?fmt(x.initialTokens):"—"}</td><td>${esc(x.email||"—")}</td><td><div class="actions"><button class="small-btn edit" onclick="editSub('${x.id}')">Edit</button><button class="small-btn archive-btn" onclick="archiveSub('${x.id}')">Remove</button><button class="small-btn remove" onclick="deleteSub('${x.id}')">Delete</button></div></td></tr>`).join("")||`<tr><td colspan="10">No subscriptions.</td></tr>`;
 $("tokenEntryCount").textContent=entries.length;$("tokenUsedTotal").textContent=fmt(used);$("tokenAllocationTotal").textContent=fmt(alloc);$("tokenCostTotal").textContent=money(tcost);$("trendLabel").textContent=monthName(state.reportMonth);$("historyCount").textContent=entries.length+" entr"+(entries.length===1?"y":"ies");
 $("tokenRows").innerHTML=entries.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.account)}</td><td><b>${esc(x.project)}</b></td><td>${fmt(x.tokens)}</td><td>${x.cost?money(x.cost):"—"}</td><td>${esc(x.notes||"—")}</td><td><div class="actions"><button class="small-btn edit" onclick="editToken('${x.id}')">Edit</button><button class="small-btn archive-btn" onclick="removeToken('${x.id}')">Remove</button><button class="small-btn remove" onclick="deleteToken('${x.id}')">Delete</button></div></td></tr>`).join("")||`<tr><td colspan="7">No token entries for ${esc(monthName(state.reportMonth))}.</td></tr>`;
 $("monthlyReportLabel").textContent=monthName(state.reportMonth);$("yearlyReportLabel").textContent=selectedYear();drawTrend(entries);save()
}
function drawTrend(entries){const c=$("trendCanvas"),dpr=devicePixelRatio||1,w=Math.max(520,c.getBoundingClientRect().width||700),h=260;c.width=w*dpr;c.height=h*dpr;let ctx=c.getContext("2d");ctx.scale(dpr,dpr);c.style.height=h+"px";let p={l:52,r:18,t:18,b:34},pw=w-p.l-p.r,ph=h-p.t-p.b,days=new Date(+state.reportMonth.slice(0,4),+state.reportMonth.slice(5,7),0).getDate(),by={};entries.forEach(e=>{let d=+e.date.slice(8,10);by[d]=(by[d]||0)+Number(e.tokens||0)});let vals=Array.from({length:days},(_,i)=>by[i+1]||0),max=Math.max(...vals,1);ctx.clearRect(0,0,w,h);ctx.strokeStyle="#e5e9f1";ctx.fillStyle="#778096";ctx.font="10px system-ui";for(let i=0;i<=4;i++){let y=p.t+ph*i/4;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke();ctx.fillText(fmt(Math.round(max*(1-i/4))),4,y+3)}ctx.beginPath();vals.forEach((v,i)=>{let x=p.l+i/(days-1)*pw,y=p.t+ph-v/max*ph;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.strokeStyle="#6847ff";ctx.lineWidth=2.5;ctx.stroke();vals.forEach((v,i)=>{if(v){let x=p.l+i/(days-1)*pw,y=p.t+ph-v/max*ph;ctx.beginPath();ctx.arc(x,y,4,0,Math.PI*2);ctx.fillStyle="#6847ff";ctx.fill()}})}
$("reportMonth").onchange=e=>{state.reportMonth=e.target.value;render()};$("newSubscriptionBtn").onclick=()=>openSub();$("newTokenBtn").onclick=()=>openToken();
function openSub(x){$("subscriptionForm").reset();$("subEditId").value=x?.id||"";$("subModalTitle").textContent=x?"Edit Subscription":"Add Subscription";$("subAlertDays").value=x?.alertDays??7;if(x){$("subProduct").value=x.product;$("subTool").value=x.tool;$("subPlan").value=x.plan;$("subStatus").value=x.status;$("subStart").value=x.start;$("subExpiry").value=x.expiry;$("subCost").value=x.cost;$("subEmail").value=x.email;$("subReminderEmail").value=x.reminderEmail;$("subInitialTokens").value=x.initialTokens;$("subPurchaseNote").value=x.purchaseNote}$("subscriptionDialog").showModal()}
window.editSub=id=>openSub(state.subscriptions.find(x=>x.id===id));window.archiveSub=id=>{if(confirm("Remove from active dashboard but keep saved data?")){let x=state.subscriptions.find(x=>x.id===id);if(x)x.archived=true;render()}};window.deleteSub=id=>{if(confirm("Permanently delete this subscription?")){state.subscriptions=state.subscriptions.filter(x=>x.id!==id);render()}};
$("subscriptionForm").onsubmit=e=>{e.preventDefault();let id=$("subEditId").value||uid("s"),old=state.subscriptions.find(x=>x.id===id),item={id,product:$("subProduct").value.trim(),tool:$("subTool").value.trim(),plan:$("subPlan").value,status:$("subStatus").value,start:$("subStart").value,expiry:$("subExpiry").value,cost:$("subCost").value,email:$("subEmail").value.trim(),reminderEmail:$("subReminderEmail").value.trim(),alertDays:Number($("subAlertDays").value||0),initialTokens:$("subInitialTokens").value,purchaseNote:$("subPurchaseNote").value.trim(),archived:old?.archived||false};let i=state.subscriptions.findIndex(x=>x.id===id);i>=0?state.subscriptions[i]=item:state.subscriptions.push(item);$("subscriptionDialog").close();render()};
function openToken(x){$("tokenForm").reset();$("tokenEditId").value=x?.id||"";$("tokenModalTitle").textContent=x?"Edit Magnific AI Token Entry":"New Magnific AI Token Entry";if(x){$("tokenDate").value=x.date;$("tokenAccount").value=x.account;$("tokenProject").value=x.project;$("tokenAmount").value=x.tokens;$("tokenCost").value=x.cost||"";$("tokenNotes").value=x.notes||""}else $("tokenDate").value=state.reportMonth+"-01";$("tokenDialog").showModal()}
window.editToken=id=>openToken(state.tokenEntries.find(x=>x.id===id));window.removeToken=id=>{if(confirm("Remove from normal view but keep saved data?")){let x=state.tokenEntries.find(x=>x.id===id);if(x)x.archived=true;render()}};window.deleteToken=id=>{if(confirm("Permanently delete this token entry?")){state.tokenEntries=state.tokenEntries.filter(x=>x.id!==id);render()}};
$("tokenForm").onsubmit=e=>{e.preventDefault();let id=$("tokenEditId").value||uid("t"),item={id,date:$("tokenDate").value,account:$("tokenAccount").value.trim(),project:$("tokenProject").value.trim(),tokens:Number($("tokenAmount").value||0),cost:$("tokenCost").value,notes:$("tokenNotes").value.trim(),archived:false};let i=state.tokenEntries.findIndex(x=>x.id===id);i>=0?state.tokenEntries[i]=item:state.tokenEntries.push(item);state.reportMonth=item.date.slice(0,7);$("tokenDialog").close();render()};
window.sendReminder=async id=>{let x=state.subscriptions.find(s=>s.id===id),to=x?.reminderEmail||x?.email;if(!to){alert("Please add Reminder Email first.");return openSub(x)}let payload={to,product:x.product,tool:x.tool,expiry:x.expiry,status:dayDiff(todayISO(),x.expiry)<0?"Overdue":"Due Soon",account:x.email||"",days:dayDiff(todayISO(),x.expiry)};try{let r=await fetch("/.netlify/functions/send-reminder",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)}),d=await r.json();if(!r.ok)throw Error(d.error||"Not configured");alert("Email reminder sent to "+to)}catch(e){if(confirm("Automatic email is not configured yet. Open your email app with a prepared reminder?"))location.href=`mailto:${encodeURIComponent(to)}?subject=${encodeURIComponent("[Subscription Alert] "+x.product+" "+payload.status)}&body=${encodeURIComponent("Subscription: "+x.product+" — "+x.tool+"\\nExpiry: "+dateText(x.expiry)+"\\nStatus: "+payload.status+"\\nAccount: "+(x.email||"—")+"\\n\\nPlease review or renew this subscription.")}`}};
function reportHtml(type){let entries=type==="month"?selectedMonthEntries():selectedYearEntries(),title=type==="month"?monthName(state.reportMonth):selectedYear(),used=entries.reduce((s,x)=>s+Number(x.tokens||0),0);return `<h1>Creative Subscription Report — ${esc(title)}</h1><div class="summary-print"><div><span>Subscriptions</span><b>${visibleSubs().length}</b></div><div><span>Alerts</span><b>${alerts().length}</b></div><div><span>Tokens Used</span><b>${fmt(used)}</b></div></div><h2>Subscriptions</h2><table><thead><tr><th>Product</th><th>Tool</th><th>Status</th><th>Expiry</th><th>Cost</th><th>Initial Tokens</th></tr></thead><tbody>${visibleSubs().map(x=>`<tr><td>${esc(x.product)}</td><td>${esc(x.tool)}</td><td>${esc(x.status)}</td><td>${dateText(x.expiry)}</td><td>${x.cost?money(x.cost):"—"}</td><td>${x.initialTokens?fmt(x.initialTokens):"—"}</td></tr>`).join("")}</tbody></table><h2>Magnific Token Usage</h2><table><thead><tr><th>Date</th><th>Account</th><th>Project</th><th>Tokens</th><th>Cost</th></tr></thead><tbody>${entries.map(x=>`<tr><td>${dateText(x.date)}</td><td>${esc(x.account)}</td><td>${esc(x.project)}</td><td>${fmt(x.tokens)}</td><td>${x.cost?money(x.cost):"—"}</td></tr>`).join("")}</tbody></table>`}
function printReport(t){$("printReport").innerHTML=reportHtml(t);setTimeout(()=>print(),30)}$("monthlyPdf").onclick=$("monthlyPdf2").onclick=()=>printReport("month");$("yearlyPdf").onclick=$("yearlyPdf2").onclick=()=>printReport("year");
$("exportJson").onclick=()=>{let b=new Blob([JSON.stringify(state,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="creative-hub-backup.json";a.click()};$("importJson").onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{state=normalize(JSON.parse(r.result));render();alert("Imported.")}catch(e){alert("Invalid JSON.")}};r.readAsText(f)};$("resetData").onclick=()=>{if(confirm("Reset to demo data?")){state=clone(DEMO);render()}};addEventListener("resize",()=>drawTrend(selectedMonthEntries()));render();